#!/bin/bash

# Redirect all output to a log file
exec > /var/log/setup_debian.log 2>&1

# Exit on any error
set -e

# Ensure script runs as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root (e.g., with sudo)."
    exit 1
fi

echo "Starting Debian system configuration..."

# --- Vim Configuration for root ---
echo "Configuring Vim for root..."
cat << EOF > /root/.selected_editor
# Generated by /usr/bin/select-editor
SELECTED_EDITOR="/usr/bin/vim.basic"
EOF

cat << EOF > /root/.vimrc
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
EOF

# --- Shell Aliases ---
echo "Setting up shell aliases..."
cat << EOF > /etc/profile.d/base.sh
# Shell aliases
alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'
alias la='ls -lah --color=auto'
EOF

# --- Open File Limits ---
echo "Configuring file and process limits..."
cat << EOF > /etc/security/limits.d/base.conf
*       -       nproc   1048576
*       -       nofile  1048576
root    -       nproc   1048576
root    -       nofile  1048576
appuser -       nproc   1048576
appuser -       nofile  1048576
EOF

# --- Install Packages ---
echo "Installing required packages..."
apt update -y
apt install -y sudo resolvconf locales systemd-timesyncd \
    vim tcpdump psmisc net-tools sysstat dstat lrzsz tmux htop curl p7zip rsync lsof tree

# --- Set Timezone ---
echo "Setting timezone to Asia/Phnom_Penh..."
timedatectl set-ntp true
timedatectl set-timezone Asia/Phnom_Penh
#dpkg-reconfigure -f noninteractive tzdata

# --- Configure Logrotate ---
echo "Configuring logrotate to use date extensions..."
if [ `grep -Ec '^dateext' /etc/logrotate.conf` -eq 0 ]; then
    if [ `grep -Ec '#dateext' /etc/logrotate.conf` -eq 1 ]; then
        sed -i 's/#dateext/dateext/g' /etc/logrotate.conf
    else
        sed -i '/# uncomment/i\# use date as a suffix of the rotated file\ndateext\n' /etc/logrotate.conf
    fi
    # Note: logrotate typically isn’t a service; forcing a run instead
    logrotate -f /etc/logrotate.conf || echo "logrotate restart skipped (not a service)"
fi

# --- Reset Crontab and Restart Cron ---
echo "Resetting crontab and restarting cron..."
(crontab -l 2>/dev/null || echo "") | crontab -
systemctl restart cron

# --- Configure Sudoers ---
echo "Configuring sudo privileges..."
cat << EOF > /etc/sudoers.d/user_sudoers
%sudo ALL=(ALL:ALL) NOPASSWD:ALL
EOF
chmod 440 /etc/sudoers.d/user_sudoers

# create user op
sudo adduser op

# --- Add User 'op' ---
echo "Creating user 'op' with sudo privileges..."
if [ `grep -c op /etc/passwd` -eq 0 ]; then
    /usr/sbin/useradd -m -s /bin/bash op
fi
# Use -aG to append sudo group safely
/usr/sbin/usermod -aG sudo op

# --- Create 'appuser' System User ---
echo "Creating system user 'appuser'..."
if [ `grep -c appuser /etc/passwd` -eq 0 ]; then
    /usr/sbin/useradd -r -d /nonexistent -s /usr/sbin/nologin -c "app runner" appuser
fi

# --- Vim Configuration for 'op' ---
echo "Configuring Vim for user 'op'..."
cat << EOF > /home/op/.selected_editor
# Generated by /usr/bin/select-editor
SELECTED_EDITOR="/usr/bin/vim.basic"
EOF

cat << EOF > /home/op/.vimrc
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
EOF

chown op:op /home/op/{.selected_editor,.vimrc}

echo "Debian configuration completed successfully!"


# make the execute file 
#nano setup_debian.sh
#chmod +x setup_debian.sh

# run this file
#sudo ./setup_debian.sh > execution_log.txt 2>&1
#sudo ./setup_debian.sh | tee execution_log.txt